# docker/Dockerfile.api
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN  --mount=type=cache,target=/root/.cache/uv uv pip install --system -r requirements.txt
# RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY . .

EXPOSE 8501 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
