name: CD Docker Build Check

on:
  push:
    branches: [ main, master ]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image (Dry Run)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
